### ISSUE TITLE
Source does not equal to path in HegelError

### ISSUE THREAD

**Issue by YevhenKap** [JSMonk/hegel#195]
I had write such code:
```typescript
class Me {
  name: string;
}

const b = new Me();
```
And get such error:
```bash
[
  HegelError: Property "name" has a type, but doesn't have an initializer!
      at /Users/ky/Projects/hobby/hegel/packages/language-server/node_modules/@hegel/core/utils/class-utils.js:379:21
      at Array.forEach (<anonymous>)
      at addClassToTypeGraph (/Users/ky/Projects/hobby/hegel/packages/language-server/node_modules/@hegel/core/utils/class-utils.js:377:64)
      at /Users/ky/Projects/hobby/hegel/packages/language-server/node_modules/@hegel/core/type-graph/type-graph.js:343:70
      at traverseTree (/Users/ky/Projects/hobby/hegel/packages/language-server/node_modules/@hegel/core/utils/traverse.js:303:3)
      at traverseTree (/Users/ky/Projects/hobby/hegel/packages/language-server/node_modules/@hegel/core/utils/traverse.js:286:9)
      at createModuleScope (/Users/ky/Projects/hobby/hegel/packages/language-server/node_modules/@hegel/core/type-graph/type-graph.js:545:28)
      at async Promise.all (index 0)
      at async createGlobalScope (/Users/ky/Projects/hobby/hegel/packages/language-server/node_modules/@hegel/core/type-graph/type-graph.js:582:19)
      at async getHegelTypings (/Users/ky/Projects/hobby/hegel/packages/language-server/server/validation/typings.js:16:31) {
    loc: { end: [Position], start: [Position] },
    source: '',
    path: '/Users/ky/Projects/hobby/cli-test/index.js'
  }
]
```
And `source` !== `path` in error. Is this bug? Or it may be in some cases?

**Comment by JSMonk** [comment]
Yes, it's a bug. `HegelError` doesn't have a `path` property. The value which placed in `path` property should be inside `source` property.

**Comment by YevhenKap** [comment]
@JSMonk I found it - `class-utils.js` there all `HegelError`s initialized without third argument.

**Comment by JSMonk** [comment]
I will fix it soon. Maybe, it will be inside other Issue.
